name: 🎭 Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: 🧪 Run E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      # Turbo cache
      - name: 💾 Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # Next.js Cache
      - name: 💾 Cache Next.js bundle
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/apps/client/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('apps/client/src/**/*.{js,jsx,ts,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nextjs-

      # Playwright browsers cache
      - name: 💾 Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: 🏗️ Install dependencies
        run: pnpm install

      - name: 🔨 Build packages
        run: pnpm build

      - name: 🎭 Install Playwright browsers
        run: pnpm --filter client exec playwright install --with-deps

      - name: 🧪 Run Playwright tests
        env:
          PLAYWRIGHT_HTML_REPORT: playwright-report
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: results.xml
          BETTERSTACK_API_KEY: ${{ secrets.BETTERSTACK_API_KEY }}
        run: pnpm test:e2e

      - name: 📊 Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            apps/client/playwright-report/
            apps/client/test-results.xml
          retention-days: 30

      - name: 📸 Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: apps/client/test-results/
          retention-days: 30
