name: 🎭 Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: 🧪 Run E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CI: true
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_CACHE: remote:rw
      BETTERSTACK_API_KEY: ${{ secrets.BETTERSTACK_API_KEY }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      # Turbo cache
      - name: 💾 Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-

      # Next.js cache
      - name: 💾 Cache Next.js bundle
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            apps/client/.next/cache
            node_modules/.cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('apps/client/src/**/*.{js,jsx,ts,tsx}') }}
          restore-keys: |
            nextjs-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-

      # Playwright browsers cache
      - name: 💾 Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: 🏗️ Install dependencies
        run: pnpm install

      - name: 🔨 Build packages
        run: pnpm build

      - name: 🎭 Install Playwright browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: pnpm --filter kasca-client exec playwright install --with-deps

      - name: 🧪 Run Playwright tests
        env:
          BETTERSTACK_API_KEY: ${{ secrets.BETTERSTACK_API_KEY }}
          NODE_ENV: test
        run: |
          touch .env
          echo BETTERSTACK_API_KEY=${{ secrets.BETTERSTACK_API_KEY }} > .env
          pnpm --filter kasca-client exec playwright test

      - name: 📊 Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            apps/client/playwright-report/
            apps/client/test-results.xml
          retention-days: 30

      - name: 📸 Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: apps/client/test-results/
          retention-days: 30
