name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_SOCKET_URL: http://localhost:3001
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      PLAYWRIGHT_HTML_REPORT: /playwright-report
      CI: true

    steps:
      - uses: actions/checkout@v4

      # Install pnpm first
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # Then setup Node.js with pnpm caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      # Cache pnpm store
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path | tr -d '\n')" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install dependencies
      - name: Install dependencies (Server)
        run: |
          cd server
          pnpm install

      - name: Install dependencies (Client)
        run: |
          cd client
          pnpm install

      # Install Playwright
      - name: Install Playwright Browsers
        run: |
          cd client
          pnpm exec playwright install --with-deps

      # Build applications
      - name: Build server
        run: |
          cd server
          pnpm build

      - name: Build client
        run: |
          cd client
          pnpm build

      # Run tests
      - name: Run Playwright tests
        run: |
          cd client
          pnpm exec playwright test
        env:
          CI: true
          NODE_ENV: test

      # Upload artifacts
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: client/test-results/
          retention-days: 30
