name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_SOCKET_URL: http://localhost:3001
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      CI: true

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
          cache-dependency-path: |
            client/pnpm-lock.yaml
            server/pnpm-lock.yaml

      - name: List directory contents
        run: |
          echo "Root directory:"
          ls -la
          echo "Server directory:"
          ls -la server/
          echo "Client directory:"
          ls -la client/

      - name: Install server dependencies
        working-directory: ./server
        run: |
          echo "Using pnpm version:"
          pnpm --version
          pnpm install --no-frozen-lockfile

      - name: Install client dependencies
        working-directory: ./client
        run: |
          echo "Using pnpm version:"
          pnpm --version
          pnpm install --no-frozen-lockfile

      - name: Install Playwright Browsers
        working-directory: ./client
        run: pnpm exec playwright install --with-deps

      - name: Start server
        working-directory: ./server
        run: |
          pnpm build
          pnpm start &
          echo "Waiting for server to start..."
          sleep 10

      - name: Build and test client
        working-directory: ./client
        run: |
          pnpm build
          pnpm exec playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: client/test-results/
          retention-days: 30
