name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_SOCKET_URL: http://localhost:3001
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      CI: true

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
          cache-dependency-path: |
            client/pnpm-lock.yaml
            server/pnpm-lock.yaml

      # Server caching
      - name: Cache server build
        uses: actions/cache@v4
        with:
          path: |
            server/dist
            server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('server/pnpm-lock.yaml', 'server/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-server-

      # Client caching
      - name: Cache client build
        uses: actions/cache@v4
        with:
          path: |
            client/.next
            client/node_modules
            client/.eslintcache
          key: ${{ runner.os }}-client-${{ hashFiles('client/pnpm-lock.yaml', 'client/tsconfig.json', 'client/next.config.mjs') }}
          restore-keys: |
            ${{ runner.os }}-client-

      # Playwright browsers cache
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('client/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install server dependencies
        if: steps.cache-server.outputs.cache-hit != 'true'
        working-directory: ./server
        run: pnpm install --no-frozen-lockfile

      - name: Install client dependencies
        if: steps.cache-client.outputs.cache-hit != 'true'
        working-directory: ./client
        run: pnpm install --no-frozen-lockfile

      - name: Install Playwright browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        working-directory: ./client
        run: pnpm exec playwright install --with-deps

      - name: Build server
        working-directory: ./server
        run: pnpm build

      - name: Start server
        working-directory: ./server
        run: |
          node dist/index.js &
          echo "Waiting for server to start..."
          sleep 10

      - name: Build client
        working-directory: ./client
        run: pnpm build

      - name: Run Playwright tests
        working-directory: ./client
        run: pnpm exec playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: client/test-results/
          retention-days: 30
